blank_issues_enabled: false
contact_links:
  - name: ‚ùì Help / Questions / Discussions
    url: https://github.com/KevinRouchut/OneSecMail/discussions
    about: Use GitHub Discussions for anything else.
